### ISSUE TITLE
Translation of "Localizing docs in Sphinx" documentation

### ISSUE THREAD

**Issue by silopolis** [authoress/sphinx-intl-demo#1]
Hello Natalia,

That excellent document you have written and which is referenced in many discussions here on GH would surely deserve more exposure and, of course, to be translated !

Would you mind sharing the sources to allow the community to give back by making your content accessible to the rest of the world ?

Thank you for the work and for sharing it openly

TY
J

**Comment by authoress** [comment]
Oh, discussions, really? If you want to translate the guide, I'll open the source, no problem. Just give me some time to review it and maybe make some recommendations.

**Comment by silopolis** [comment]
Le mar. 22 nov. 2022 à 18:34, Natalia ***@***.***> a écrit :

> Oh, discussions, really?
>
Yes indeed ! I found it searching for `sphinx-intl` on GH to see how others
are implementing it and found your guide referenced several times :)
Actually, that search was triggered by discussion on the matter for the
Write The Docs project https://github.com/writethedocs/www/issues/1155

If you want to translate the guide, I'll open the source, no problem.
>
Awesome ! I would gladly translate it to French for sure :)
Plus it would be nice to have the guide itself implementing its own
recipe... Eat your own dog food style ;)

> Just give me some time to review it and maybe make some recommendations.
>
Of course, take it easy, I have more than enough in my plate already 😅

**Comment by authoress** [comment]
Here you are: https://github.com/authoress/sphinx-intl-guide

**Comment by silopolis** [comment]
Le jeu. 24 nov. 2022 à 11:57, Natalia ***@***.***> a écrit :

> Here you are: https://github.com/authoress/sphinx-intl-guide
>
Awesomely awesome 😍
Didn't expect it that early 💥🙏
So, let's push it up in the French translation to-do, just after
sphinx-intl !

Thank you very much

TY
J

PS: If you care to do the same with the miniconda guide... :)

**Comment by authoress** [comment]
You are welocome ))
Miniconda is a little tricky to translate since the source is written in Russian and then translated into English.

**Comment by silopolis** [comment]
Le jeu. 24 nov. 2022 à 14:09, Natalia ***@***.***> a écrit :

> Miniconda is a little tricky to translate since the source is written in
> Russian and then translated into English.
>

I have to confess sub zero skills in Russian! 😅
But, even if unorthodox (pun intended 😉) I could do it from the English
version. Transifex editor even gives you the choice of source language for
translation... And this will stay between you and me 🤫

**Comment by authoress** [comment]
Well, let's get back to Miniconda when we're done with sphinx-intl, okay?
And I'm closing this issue.

**Comment by silopolis** [comment]
Le ven. 25 nov. 2022 à 09:39, Natalia ***@***.***> a écrit :

> Well, let's get back to Miniconda when we're done with sphinx-intl, okay?
>
Absolutely ! 👍
